# Generated by Django 5.2.8 on 2025-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodlog',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='periodlog',
            name='flow_level',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='periodlog',
            name='mood',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='periodlog',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='periodlog',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
    ]
